version: '3.1'

services:

  adminer:
    image: adminer
    # image: dockette/adminer:full-php5
    restart: always
    ports:
      - 8080:8080

  dbPostgres:
    image: postgres:10
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: changeme
        POSTGRES_DB: mydb

  dbMysql:
    image: mysql:8.0.3
    restart: always
    environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: mydb